### ISSUE TITLE
java.lang.IllegalStateException: Stopwatch is not running

### ISSUE THREAD

**Issue by pmajkutewicz** [lwaddicor/spring-startup-analysis#5]
Steps to reproduce:
1. Add dependency to pom:
```
<dependency>
    <groupId>com.github.lwaddicor</groupId>
    <artifactId>spring-startup-analysis</artifactId>
    <version>1.0.0</version>
</dependency>
```
2. Add beans
```
<bean class="com.github.lwaddicor.springstartupanalysis.web.SpringStartupController"/>
<bean class="com.github.lwaddicor.springstartupanalysis.StartProgressBeanPostProcessor"/>
```
3. Build, run, go to /spring-startup/ page

**Result**:
```ERROR [22 Feb 2017 09:48:38,252][org.springframework.web.servlet.FrameworkServlet]: Context initialization failed
java.lang.IllegalStateException: Stopwatch is not running. 
        at org.apache.commons.lang3.time.StopWatch.stop(StopWatch.java:204)
        at com.github.lwaddicor.springstartupanalysis.StartProgressBeanPostProcessor.onApplicationEvent(StartProgressBeanPostProcessor.java:56)
        at com.github.lwaddicor.springstartupanalysis.StartProgressBeanPostProcessor.onApplicationEvent(StartProgressBeanPostProcessor.java:20)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:954)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
        at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:651)
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:602)
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:665)
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:521)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:462)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:779)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)```

**Comment by lwaddicor** [comment]
Hi.
I noticed it does this yesterday when not in a spring boot application. Will investigate later today

**Comment by snussbaumer** [comment]
same here, in a spring boot 1.5 application

**Comment by lwaddicor** [comment]
Going to have a look at this now

**Comment by lwaddicor** [comment]
I've made some changes which should help this. I've committed them but i'll do some further testing later. 

If they looks alright i'll do a release so you can pick them up via maven central

**Comment by pmajkutewicz** [comment]
Hmm, still having issues:
```Caused by: java.lang.IllegalStateException: Stopwatch is not running. 
        at org.apache.commons.lang3.time.StopWatch.stop(StopWatch.java:204)
        at com.github.lwaddicor.springstartupanalysis.StartProgressBeanPostProcessor.postProcessAfterInitialization(StartProgressBeanPostProcessor.java:59)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:409)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1657)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:112)
        ... 41 more
```

**Comment by lwaddicor** [comment]
That is quite strange.

When the bean gets initialised it adds a pre-started Stopwatch to a map with the bean name as the key.
When the bean is finished being initialised it asks the map for the stopwatch and then stops it. 

The only way it could get a 'Stopwatch is not running.' error, as far as i know, would be if the postProcessAfterInitialization was being called twice with same bean name.

I'll change it so that it checks it is running before it stops it, which should stop the error happening. Might end up with a weird time for one of the beans though.

**Comment by pmajkutewicz** [comment]
<a href="https://ibb.co/mnqoGF"><img src="https://thumb.ibb.co/mnqoGF/img.jpg" alt="img" border="0"></a>

OK, looks good.
Still can't access spring-startup endpoint directly - but I guess this is problem of app configuration.
Thanks.

**Comment by lwaddicor** [comment]
Yeah i think so. Perhaps its because it needs a / on the end e.g. http://localhost:8080/spring-startup/

I'll try and do a release shortly
